print("Welcome to Email_Permurator")
first_name=input("Enter the Firstname ")
Last_name=input("Enter the Lastname ")
Domain=input("Enter Domain name ")
print("Here you combinations")
print(first_name+"_"+Last_name +"@"+ Domain)
print(first_name+Last_name +"@"+ Domain)
print(first_name+"@"+ Domain)
print(Last_name +"@"+ Domain)
print(first_name[0]+Last_name +"@"+ Domain)
print(first_name+"."+Last_name +"@"+ Domain)
print(first_name+Last_name[0] +"@"+ Domain)
#print(first_name+"_"+Last_name +"@"+ Domain)
#print(first_name+"_"+Last_name +"@"+ Domain)
#print(first_name+"_"+Last_name +"@"+ Domain)
